#!/bin/sh
path=$(pwd)

# HOME
ln -sf "$path/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$path/.zshenv" "$HOME/.zshenv"
ln -sf "$path/.zshrc" "$HOME/.zshrc"
ln -sf "$path/battery.sh" "$HOME/battery.sh"

# CONFIG
[ ! -d "$HOME/.config" ] && mkdir -p "$HOME/.config"

for dir in "$path/.config"/*; do
    name=$(basename "$dir")
    target="$HOME/.config/$name"

    if [ -e "$target" ] && [ ! -L "$target" ]; then
        echo "⚠️  La carpeta '$name' ya existe en ~/.config"
        read -p "¿Reemplazar? (y/n): " choice
        case "$choice" in
            y|Y)
                mv "$target" "$target.backup_$(date +%Y%m%d_%H%M%S)"
                ln -sfn "$dir" "$target"
                echo "✅ '$name' reemplazada (se creó un respaldo)."
                ;;
            *)
                echo "⏩ Se mantuvo '$name'."
                ;;
        esac
    else
        ln -sfn "$dir" "$target"
        echo "✅ '$name' enlazada correctamente."
    fi
done

#Local
[ -d $HOME/.local/share/fonts ] && rm -r $HOME/.local/share/fonts
ln -sf $path/.local/share/fonts $HOME/.local/share/fonts

echo "✨ Configuración completada."
