#!/usr/bin/env bash

# Calculate where the image should be placed on the screen.
num="$(printf "%0.f\n" "$(echo "$(tput cols) / 2" | bc)")"
numb="$(printf "%0.f\n" "$(echo "$(tput cols) - $num - 1" | bc)")"
numc="$(printf "%0.f\n" "$(echo "$(tput lines) - 2" | bc)")"

image() {
	if [ -n "$DISPLAY" ]; then
		declare -p -A cmd=([action]=add [identifier]="PREVIEW" \
			[x]="$2" [y]="$3" [max_width]="$4" [max_height]="$5" \
			[path]="$1") > "$FIFO_UEBERZUG"
		exit 1
	else
		chafa "$1" -s "${4}x${5}"
	fi
}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

case "$(echo "$1" | awk '{print tolower($0)}')" in
	*.tar.gz) tar tzf "$1" ;;
	*.tar.bz2|*.tbz2) tar tjf "$1" ;;
	*.tar) tar tf "$1" ;;
	*.zip|*.jar) unzip -l "$1" | awk '{for(i=4;i<=NF-1;i++) printf $i" "; print $NF}' ;;
	*.rar) unrar l "$1" | awk '{for(i=5;i<=NF-1;i++) printf $i" "; print $NF}';;
	*.iso) iso-info --no-header -l "$1" ;;
	*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp)
		image "$1" "$num" 1 "$numb" "$numc"
		;;
	*.pdf|*.docx|*.wav|*.mp3|*.mp4)	;;
	*) source-highlight -q --outlang-def=esc.outlang --style-file=esc.style -i "$1" || cat -- "$1" ;;
esac
exit 0
