#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh
bspc monitor -d 1 2 3 4

bspc config border_width         1
bspc config window_gap           0
bspc config top_padding          0
bspc config focused_border_color  "#1E8EFF"
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a LibreWolf desktop='^1' follow=on
bspc rule -a Pcmanfm desktop='^3' follow=on
